server:
  port: 8085

spring:
  application:
    name: batch-service
  config:
    import: "optional:configserver:http://config-server:8888"
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:file:${BATCH_DB_PATH:./batchdb};DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

batch:
  input-directory: ${BATCH_INPUT_DIRECTORY:../bank-api/src/main/resources/data/legacy}
  output-directory: ${BATCH_OUTPUT_DIRECTORY:./output}
  rates:
    savings-monthly: ${BATCH_SAVINGS_MONTHLY_RATE:0.005}
    loan-monthly: ${BATCH_LOAN_MONTHLY_RATE:0.020}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
