spring.application.name=bff-banco-xyz
server.port=8080

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Rutas de archivos legacy
legacy.data.path=../bank_legacy_data-main/data/semana_3