# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz_batch?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tablas automáticas de Spring Batch
spring.batch.jdbc.initialize-schema=always

# Desactivar ejecución automática al arranque
spring.batch.job.enabled=false