# ===================================================================
# CONFIGURACION DE BASE DE DATOS (MySQL)
# ===================================================================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/banco_xyz_batch?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURACION JPA / HIBERNATE
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===================================================================
# CONFIGURACION SPRING BATCH
# ===================================================================
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# ===================================================================
# PARAMETROS DE ESCALAMIENTO Y RESILIENCIA (TUNING BATCH)
# ===================================================================
batch.tuning.chunk-size=5
batch.tuning.core-pool-size=3
batch.tuning.max-pool-size=5
batch.tuning.queue-capacity=20
batch.tuning.thread-prefix=banco-thread-
batch.tuning.max-skip-count=5
batch.tuning.max-retry-attempts=3